spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
  jpa:
    hibernate:
      ddl-auto: validate

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
