spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/geupjido}
    username: ${DB_USERNAME:geupjido}
    password: ${DB_PASSWORD:geupjido-local}
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  jpa:
    hibernate:
      ddl-auto: validate

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
